--SEQUENCE
SELECT * FROM USER_SEQUENCES;

CREATE SEQUENCE TEST_SEQ
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999;

--간접실행 : query문에 넣어서 사용하는 것.
--CURRVAL은 메모리에 올라와있는 SEQUENCE의 현재값을 얻는 일만 수행
SELECT TEST_SEQ.CURRVAL
FROM DUAL;

--NEXTVAL
SELECT TEST_SEQ.NEXTVAL
FROM DUAL;

--SEQUENCE 삭제
DROP SEQUENCE TEST_SEQ;


--1에서부터 9999999999까지 10씩 증가하는 SEQ
CREATE SEQUENCE SEQ
INCREMENT BY 10
START WITH 1
MAXVALUE 9999999999
CACHE 100
CYCLE;

SELECT SEQ.NEXTVAL
FROM DUAL;

DROP SEQUENCE SEQ;

--쿼리문이 실패하면 번호가 사라진다.
ALTER TABLE TEST MODIFY NAME VARCHAR2(15);
INSERT INTO TEST(NUM,NAME) VALUES (TEST_SEQ.NEXTVAL,'테스트');
SELECT * FROM TEST;
