select * from EMP;
SELECT EMPNO,JOB,ENAME,SAL,DEPTNO
FROM EMP
WHERE DEPTNO = 10;

SELECT ENAME,EMPNO,HIREDATE,SAL,COMM,JOB
FROM EMP
WHERE JOB = 'SALESMAN';

SELECT EMPNO, ENAME, DEPTNO, SAL, HIREDATE
FROM EMP
WHERE DEPTNO = 10 OR DEPTNO = 20;

SELECT EMPNO, ENAME, DEPTNO, SAL, HIREDATE
FROM EMP
WHERE (DEPTNO = 10 OR DEPTNO = 20) AND SAL > 1000;

SELECT EMPNO, ENAME, SAL, COMM, DEPTNO
FROM EMP
WHERE COMM IS NULL;

SELECT EMPNO, ENAME, DEPTNO, SAL, HIREDATE
FROM EMP
WHERE SAL >= 1000 AND SAL <= 3000;

SELECT EMPNO,ENAME,MGR,DEPTNO
FROM EMP
WHERE MGR IN(7902,7698,7566);


SELECT EMPNO,ENAME,DEPTNO,SAL,SAL*0.033 TAX
FROM EMP;

SELECT EMPNO, ENAME,SAL, SAL/12 MONTH_MONEY
FROM EMP;

SELECT '['||ENAME||']사원의 사원번호는['|| EMPNO ||']'
FROM EMP;

SELECT ENAME,EMPNO
FROM EMP
WHERE ENAME LIKE 'A%';

SELECT ENAME, EMPNO
FROM EMP
WHERE ENAME LIKE '%S';

SELECT ENAME, EMPNO
FROM EMP
WHERE ENAME LIKE '%A%';

--사원테이블에서 사원명에 'L'이 두개 들어있는 사원의 사원명 사원번호를 조회
SELECT ENAME, EMPNO
FROM EMP
WHERE ENAME LIKE '%L%L%';

-- 사원테이블에서 사원명이 5글자이면서 세번째 문자가 'A' 인 사원명을 조회하세요
SELECT ENAME
FROM EMP
WHERE ENAME LIKE '__A__';

DROP TABLE ZIPCODE;

--- 우편번호 테이블 생성. (우펀번호, 시도,구군,동,번지,SEQ)
CREATE TABLE ZIPCODE(
ZIPCODE CHAR(7),
SIDO CHAR(6),
GUGUN VARCHAR(25),
DONG VARCHAR2(300),
BUNJI VARCHAR2(30),
SEQ NUMBER(5)
);

SELECT COUNT(*) FROM ZIPCODE;

TRUNCATE TABLE ZIPCODE;

-- 우편번호조회 : 상도동
SELECT ZIPCODE,SIDO,GUGUN,DONG,BUNJI
FROM ZIPCODE
WHERE DONG LIKE '개봉2동%';

--사원 테이블에서 중복되는 직무를 제외하고 조회하자.
SELECT DISTINCT JOB
FROM EMP;

--사원 테이블에서 매니저번호를 조회하세요 (중복배제)
SELECT DISTINCT MGR
FROM EMP;

--GROUP BY의 사용
SELECT JOB
FROM EMP
GROUP BY JOB;

SELECT DEPTNO
FROM EMP
GROUP BY DEPTNO;

--그룹으로 묶여지지 않은 컬럼이 조회컬럼에 정의되면 error
SELECT DEPTNO, ENAME
FROM EMP
GROUP BY DEPTNO, ENAME;
