CREATE OR REPLACE PROCEDURE INSERT_PROC( EMPNO IN NUMBER, ENAME IN VARCHAR2, SAL IN NUMBER,
 CNT OUT NUMBER, MSG OUT VARCHAR2)

IS

	I_EMPNO NUMBER;

BEGIN

	I_EMPNO := EMPNO;

	IF EMPNO > 9999 THEN
	I_EMPNO := 0;
	END IF;

	INSERT INTO TEST_PROC (EMPNO, ENAME, SAL, HIREDATE) VALUES (I_EMPNO,ENAME,SAL,SYSDATE);

	CNT :=SQL%ROWCOUNT;

	IF CNT = 1 THEN
	COMMIT;
	MSG := '정보가 추가되었습니다.';
	END IF;

  EXCEPTION
  WHEN OTHERS THEN
  MSG :=SQLERRM || '('|| sqlerrm ||')정보가 추가되지 않았습니다.';
END;
/


--SELECT * FROM TEST_PROC;
--TRUNCATE TABLE TEST_PROC;
--
--var CNT NUMBER;
--VAR MSG VARCHAR2(2000);
--
--exec INSERT_PROC(1,'이우길',3000,:CNT,:MSG);
--
--PRINT CNT
