CREATE TABLE TEST_PROC AS (SELECT EMPNO, ENAME, SAL, HIREDATE FROM EMP WHERE 1=0);
SELECT * FROM TEST_PROC;

CREATE OR REPLACE PROCEDURE INSERT_PROC( EMPNO IN NUMBER, ENAME IN VARCHAR2, SAL IN NUMBER,
 CNT OUT NUMBER, MSG OUT VARCHAR2)

IS

BEGIN

	IF EMPNO > 9999 THEN
	EMPNO := 0;
	END IF;

END;
/