--ALTER
--테이블 조작
CREATE TABLE TEST_ALTER(
	NUM NUMBER,
	NEAM VARCHAR2(30),
	ID VARCHAR2(20),
	ADDR NUMBER
);

--column명 변경
--NEAM을 NAME로 변경
ALTER TABLE TEST_ALTER RENAME COLUMN NEAM to NAME;

--column의 Datatype 변경
--레코드가 존재하지 않을 때 Datatype 자체를 변경 가능
--ADDR의 NUMBER을 VARCHAR2(300)으로 변경
ALTER TABLE TEST_ALTER MODIFY ADDR VARCHAR2(300);

INSERT INTO TEST_ALTER(NUM,NAME,ID,ADDR)
VALUES
(1,'TEST','LEE','서울시');

INSERT INTO TEST_ALTER(NUM,NAME,ID,ADDR)
VALUES
(2,'TEST','','서울시');

--확인
SELECT * FROM TEST_ALTER;
COMMIT;

--레코드가 존재하면 Datatype은 크기만 변경 가능
ALTER TABLE TEST_ALTER MODIFY ADDR NUMBER; --ERROR
ALTER TABLE TEST_ALTER MODIFY ADDR VARCHAR2(30);

--MODIFY로 컬럼단위 제약조건을 추가할 수 있다.
--레코드가 존재하면 레코드의 값중 추가할 제약사항에 위배되는 값이 있다면 추가하지 못한다.
--추가하려면 제약조건에 위배되는 레코드를 삭제 후 추가

DELETE FROM TEST_ALTER WHERE NUM = 2;
COMMIT;
ALTER TABLE TEST_ALTER MODIFY ID VARCHAR2(30) CONSTRAINT PK_TEST_ALTER PRIMARY KEY;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'TEST_ALTER';

--column의 삭제
--ID column삭제 제약사항이 있다면 같이 삭제
ALTER TABLE TEST_ALTER DROP COLUMN ID;

--column의 추가
--column을 추가하면서 제약사항을 추가할 수 있다. 추가되는 column은 제일 마지막에 추가
--age추가 나이는 20~40대 까지의 나이를 추가할 수 있도록
ALTER TABLE TEST_ALTER ADD AGE NUMBER(2) CHECK(AGE BETWEEN 20 AND 49);

INSERT INTO TEST_ALTER(NUM,NAME,ADDR,AGE)
VALUES
('2','TEST2','서울시',25);

SELECT * FROM TEST_ALTER;



--제약 사항의 처리
TRUNCATE TABLE TEST_ALTER;
ALTER TABLE TEST_ALTER ADD ID VARCHAR2(30) CONSTRAINT PK_TEST_ALTER PRIMARY KEY;

--제약사항 삭제
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'TEST_ALTER';
--ID에 설정된 기본키 조건 삭제
ALTER TABLE TEST_ALTER DROP CONSTRAINT PK_TEST_ALTER;
ALTER TABLE TEST_ALTER DROP CONSTRAINT SYS_C008755;

--제약사항 추가
--ID에 다시 기본키 제약조건 추가
ALTER TABLE TEST_ALTER ADD CONSTRAINT PK_TEST_ALTER PRIMARY KEY(ID);
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'TEST_ALTER';

--제약사항 비활성 화 하기
ALTER TABLE TEST_ALTER DISABLE CONSTRAINT PK_TEST_ALTER;
SELECT * FROM TEST_ALTER;
INSERT INTO TEST_ALTER(NUM,NAME,ADDR,AGE,ID)
VALUES
('1','TEST2','서울시',25,'1');

INSERT INTO TEST_ALTER(NUM,NAME,ADDR,AGE,ID)
VALUES
('2','TEST3','서울시',25,'1');

SELECT * FROM TEST_ALTER;

ALTER TABLE TEST_ALTER ENABLE CONSTRAINT PK_TEST_ALTER; --ERROR

--계정 관리
--sqlplus "/as SYSDB" 로 접근

--계정 생성
--C##으로 시작하는 계정이 아닌 계정 생성
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

--계정 생성
CREATE USER lwg IDENTIFIED BY 1234;

SELECT * FROM DBA_USERS;

--생성된 계정에 접속, 사용권한 주기
GRANT CONNECT, RESOURCE TO LWG;

--생성된 계정이 사용할 tablespace 설정
ALTER USER lwg DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

SELECT * FROM DBA_USERS WHERE USERNAME = 'LWG';

--계정 닫기
ALTER USER lwg ACCOUNT LOCK;

--계정 풀기
ALTER USER lwg ACCOUNT UNLOCK;

--관리자 계정의 다른 계정의 비밀번호를 변경할 수 있다.
ALTER USER lwg IDENTIFIED BY 1234;

--계정 삭제.
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
DROP USER lwg;


--권한 삭제
SELECT * FROM DBA_USERS;
REVOKE CONNECT FROM scott;

GRANT CONNECT to scott;

SELECT * FROM USER_OBJECTS;

DROP TABLE ZIPCODE;
PURGE RECYCLEBIN;

DROP TABLE ZIPCODE;
SELECT * FROM USER_INDEXES;

DROP TABLE UNIQUE_TABLE;
