CREATE TABLE student(
NAME VARCHAR2(20),
ADDR VARCHAR2(60),
AGE NUMBER(3),
BLOODTYPE CHAR(2),
GERDER CHAR(3),
INPUT_DATE DATE);

INSERT INTO STUDENT
(NAME, ADDR, AGE, BLOODTYPE, GERDER, INPUT_DATE)
VALUES
('김현규','경기도 파주시',26,'A','남',SYSDATE);

INSERT INTO STUDENT
(NAME, ADDR, AGE, BLOODTYPE, GERDER, INPUT_DATE)
VALUES
('박지원','서울시 동대문구 동대문동',24,'AB','여',SYSDATE);

INSERT INTO STUDENT
(NAME, ADDR, AGE, BLOODTYPE, GERDER, INPUT_DATE)
VALUES
('이우길','인천시 미추홀구 미추홀동',28,'O','남',SYSDATE);

INSERT INTO STUDENT
(NAME, ADDR, AGE, BLOODTYPE, GERDER, INPUT_DATE)
VALUES
('이우길이','서울시 종로구 종로동',30,'A','남',SYSDATE);

INSERT INTO STUDENT
(NAME, ADDR, AGE, BLOODTYPE, GERDER, INPUT_DATE)
VALUES
('최은혜','수원시 영통구 망포동',27,'B','여',SYSDATE);

commit;

SELECT * FROM STUDENT;

UPDATE STUDENT
SET ADDR = '서울시 종로구 경복궁'
WHERE NAME = '이우길이';

SELECT * FROM STUDENT;

UPDATE STUDENT
SET AGE = 45
WHERE NAME = '이우길이';

SELECT * FROM STUDENT;

COMMIT;

SAVEPOINT work_4;

DELETE FROM STUDENT
WHERE NAME = '이우길이';

SELECT * FROM STUDENT;

ROLLBACK TO work_4;

SELECT * FROM STUDENT;

TRUNCATE TABLE STUDENT;

SELECT * FROM STUDENT;

DROP TABLE STUDENT;

SELECT * FROM TAB;

FLASHBACK TABLE STUDENT TO BEFORE DROP;

SELECT * FROM TAB;

DROP TABLE STUDENT;

PURGE RECYCLEBIN;

SELECT * FROM TAB;

DROP TABLE STUDENT;

SELECT * FROM TAB;

PURGE RECYCLEBIN;

SELECT * FROM TAB;
