-- Primary key

--column단위
--이름 아이디 주소를 저장할 수 있는 테이블 생성
CREATE TABLE PRIMARY_COLUMN(
	NAME VARCHAR2(15),
	ID VARCHAR2(20) CONSTRAINT PK_PRIMARY_COLUMN PRIMARY KEY,
	ADDR VARCHAR2(300)
);

SELECT * FROM USER_INDEXES;

SELECT * FROM USER_CONSTRAINTS;

INSERT INTO PRIMARY_COLUMN(NAME, ID, ADDR)VALUES('테스트','test','테스트');

COMMIT;


--table 제약사항
--번호, 이름 , 주민번호 저장
CREATE TABLE PRIMARY_TABLE(
	NUM NUMBER,
	NAME VARCHAR2(10),
	SSN CHAR(14),
	CONSTRAINT PK_PRIMARY_TABLE PRIMARY KEY(SSN)
);

-- 추가성공.
--최초입력
INSERT INTO PRIMARY_TABLE(NUM, NAME, SSN)VALUES(1,'test','880101-1234567');

--주민번호가 다르다면
--추가 성공
INSERT INTO PRIMARY_TABLE(NUM, NAME, SSN)VALUES(1,'test','880101-1234568');

SELECT * FROM PRIMARY_TABLE;


commit;

--ERROR
--같은 주민번호가 입력되었을 때
INSERT INTO PRIMARY_TABLE(NUM, NAME, SSN)VALUES(2,'test-2','880101-1234568');

--null이 입력될 때
INSERT INTO PRIMARY_TABLE(NUM, NAME, SSN)VALUES(3,'test-2','');



--여러개의 column이 하나의 PRIMARY KEY로 구성될 때 (복합키가 기본기인경우)
--번호, 아이템명, 생산일, 설명, 생산일

CREATE TABLE PRIMARY_MULTI(
	NUM NUMBER,
	ITEM VARCHAR2(50),
	INFO VARCHAR2(4000),
	PRD_DATE VARCHAR(20),
	CONSTRAINT PK_PRIMARY_MULTI PRIMARY KEY(ITEM,PRD_DATE)
	);

