--view
CREATE OR REPLACE VIEW V_CP_EMP AS (SELECT * FROM CP_EMP4);

--권한 부여
GRANT CREATE VIEW TO scott;

SELECT * FROM DBA_SYS_PRIVS
WHERE GRANTEE = 'SCOTT';

--view조회
SELECT * FROM USER_VIEWS;

--VIEW를 이용한 조회
SELECT * FROM CP_EMP4;

SELECT * FROM V_CP_EMP;

--VIEW에서 DML 사용하기
INSERT INTO V_CP_EMP(EMPNO,ENAME)
VALUES
(1111,'이우길');

UPDATE V_CP_EMP
SET EMPNO = 2222
WHERE ENAME = '이우길';

DELETE FROM V_CP_EMP
WHERE EMPNO=2222;


INSERT INTO CP_EMP4(EMPNO,ENAME)
VALUES
(1111,'이우길');

--VIEW의 삭제
DROP VIEW V_CP_EMP;

SELECT * FROM USER_VIEWS;

--복합 view
CREATE TABLE CP_DEPT AS (SELECT * FROM DEPT);
CREATE TABLE CP_EMP AS (SELECT * FROM EMP);

CREATE VIEW V_DEPT AS
(SELECT d.DEPTNO,d.DNAME,d.LOC,e.EMPNO,e.ENAME,e.JOB,e.HIREDATE
FROM DEPT d, EMP e
WHERE (e.DEPTNO(+) = d.DEPTNO));

SELECT * FROM V_DEPT;

--view를 사용하면 조인하지 않아도 서로다른 테이블의 레코드를 얻을 수 있다.
SELECT DEPTNO,DNAME,LOC,EMPNO,ENAME,JOb,HIREDATE
FROM V_DEPT;

--복합 view에 DML사용
--INSERT ERROR
INSERT INTO V_DEPT (DEPTNO,DNAME,LOC,EMPNO,ENAME,JOb,HIREDATE)
VALUES
(50,'개발부','KOREA',7839,'KINGKIGN','개발자',SYSDATE);

--VIEW의 변경
CREATE OR REPLACE VIEW V_DEPT AS
(SELECT d.DEPTNO,d.DNAME,d.LOC,e.EMPNO,e.ENAME
FROM DEPT d, EMP e
WHERE (e.DEPTNO(+) = d.DEPTNO));

--VIEW 삭제
DROP VIEW V_DEPT;
