--시스템 사용권한 보기
--관리자 계정에서 가능
SELECT * FROM DBA_ROLE_PRIVS
WHERE GRANTEE='SCOTT';

--쿼리문 생성 권한
SELECT * FROM DBA_SYS_PRIVS
WHERE GRANTEE='SCOTT';
--시노님생성
--CP_EMP4 테이블의 SYNONYM을 CD4로 설정
CREATE SYNONYM CD4 FOR CP_EMP4;

--권한 설정
GRANT CREATE SYNONYM TO scott;

SELECT * FROM CD4;
