--CHECK, NOT NULL, DEFAULT
--이름, 성별, 나이, 입력일을 저장하는 테이블을 생성
--이름 필수 입력
--성별은 남자 또는 여자 값만 입력
--나이는 null이 입력되면 0이 추가
--입력일이 생략되면 insert하는 시점의 현재 날자를 입력
CREATE TABLE OTHER_CONSTRAINT(
NAME VARCHAR2(12) NOT NULL,
GENDER CHAR(6) CHECK(GENDER IN('남자','여자')),
AGE NUMBER(3) DEFAULT 0,
INPUT_DATE DATE DEFAULT SYSDATE
);

--추가 성공
INSERT INTO OTHER_CONSTRAINT
(NAME,GENDER,AGE,INPUT_DATE)
VALUES
('이우길','남자',25,'1996-11-27');

INSERT INTO OTHER_CONSTRAINT
(NAME,GENDER)
VALUES
('이우순','여자');

select * from OTHER_CONSTRAINT;

--추가 실패
INSERT INTO OTHER_CONSTRAINT
(NAME,GENDER,AGE,INPUT_DATE)
VALUES
('','몰라',25,'1996-11-27');

INSERT INTO OTHER_CONSTRAINT
(NAME,GENDER,AGE,INPUT_DATE)
VALUES
('이우길','몰라',25,'1996-11-27');

--USER_CONSTAINTS : 테이블에 설정된 제약사항 확인 DICTIONARY
--USER_CONS_COLUMNS : 테이블에 설정된 제약사항column을 확인하는 DICTIONARY
--USER_TAB_COLS : 테이블에 존재하는 COLUMN명, DATATYPE, 크기, DEFAULT 등을 확인할 수 있는 DICTIONARY

SELECT * FROM USER_TAB_COLS
WHERE TABLE_NAME ='OTHER_CONSTRAINT';

DROP TABLE OTHER_CONSTRAINT;
PURGE RECYCLEBIN;
