--사원번호,사원명,입사일,부서번호,부서명,위치 조회
--ANSI
SELECT EMPNO,ENAME,HIREDATE,DEPT.DEPTNO,DNAME,LOC
FROM DEPT
INNER JOIN EMP
ON DEPT.DEPTNO = EMP.DEPTNO ;

SELECT e.EMPNO,e.ENAME,e.HIREDATE,d.DEPTNO,d.DNAME,d.LOC
FROM DEPT d , EMP e
WHERE (d.DEPTNO = e.DEPTNO);

select * from CAR_COUNTRY;
select * from CAR_MAKER;
select * from CAR_MODEL;

--제조국이 '국산'인 차량의 제조사, 모델명, 년식, 가격, 옵션을 조회
SELECT C_COU.MAKER,C_MOD.MODEL,C_MOD.CAR_YEAR,C_MOD.PRICE,C_MOD.CAR_OPTION
FROM 				CAR_COUNTRY C_COU, CAR_MAKER		C_MAK, CAR_MODEL		C_MOD
WHERE(C_MAK.MAKER = C_COU.MAKER AND C_MAK.MODEL = C_MOD.MODEL) AND C_COU.COUNTRY = '국산';

--차량의 옵션에 ABS가 있는 모든 차량의 제조국,제조사,모델명,년식,배기량,이미지,입력일 조회
SELECT	C_COU.COUNTRY,C_COU.MAKER,C_MOD.MODEL,C_MOD.CAR_YEAR,C_MOD.CC,C_MOD.CAR_IMG, C_MOD.HIREDATE
FROM  CAR_COUNTRY C_COU, CAR_MAKER		C_MAK, CAR_MODEL		C_MOD
WHERE (C_MAK.MAKER = C_COU.MAKER AND C_MAK.MODEL = C_MOD.MODEL)	AND CAR_OPTION LIKE '%ABS%';


--OUTER JOIN
SELECT d.DEPTNO,d.DNAME,d.LOC,e.EMPNO,e.ENAME,e.JOB,e.HIREDATE
FROM DEPT d LEFT JOIN EMP e
ON e.DEPTNO = d.DEPTNO;

SELECT d.DEPTNO,d.DNAME,d.LOC,e.EMPNO,e.ENAME,e.JOB,e.HIREDATE
FROM DEPT d , EMP e
WHERE e.DEPTNO(+) = d.DEPTNO;

--제조사가 현대, 기아 인 모든 차량의 제조사, 모델명 가격 연식 조회
SELECT C_MAK.MAKER,C_MAK.MODEL,C_MOD.PRICE,C_MOD.CAR_YEAR
FROM   CAR_MAKER C_MAK, CAR_MODEL	C_MOD
WHERE (C_MOD.MODEL(+) = C_MAK.MODEL) AND C_MAK.MAKER IN('현대','기아');

--모든 부서에 근무하는 사원들의 부서번호 부서명 위치 사원번호
--사원명 연봉 우편번호 시도 구군 동 번지 조회
--사원테이블과 우편번호 테이블은 사원번호와 SEQ로 조인 조건을 설정
select * from ZIPCODE;

SELECT d.DEPTNO,d.DNAME,d.LOC,e.EMPNO,e.ENAME,e.SAL,z.ZIPCODE,z.SIDO,z.GUGUN,z.DONG,z.BUNJI
FROM DEPT d
LEFT JOIN EMP e
ON e.DEPTNO = d.DEPTNO
LEFT JOIN ZIPCODE z
ON z.SEQ = e.EMPNO
ORDER BY d.DEPTNO;

SELECT d.DEPTNO,d.DNAME,d.LOC,e.EMPNO,e.ENAME,e.SAL,z.ZIPCODE,z.SIDO,z.GUGUN,z.DONG,z.BUNJI
FROM  DEPT d , EMP e , ZIPCODE z
WHERE (e.DEPTNO(+) = d.DEPTNO AND z.SEQ(+) = e.EMPNO);

--사원테이블에서 사원명이 'ALLEN'인 사원보다 연봉을 많이 받는 사원의
--사원번호,사원명,입사일,연봉,직무조회
SELECT EMPNO,ENAME,SAL,JOB
FROM EMP
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME ='ALLEN');

SELECT e1.EMPNO, e1.ENAME ,e1.SAL, e1.JOB
FROM  EMP e1 , EMP e2
WHERE (e1.SAL > e2.SAL) AND e2.ENAME = 'ALLEN';
